export const metadata = {
  title: "Terms — omicron",
  description: "The rules of the road for using Four.",
};

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-6 pt-16 pb-32 space-y-8">
      <div>
        <h1 className="mb-4">Terms</h1>
        <p className="muted">Last updated 2 June 2026</p>
      </div>

      <p>
        By using Four you agree to the following. The short version: be a
        reasonable person, do not break the site, do not use the AI to harm
        anyone, and you can cancel your subscription any time.
      </p>

      <section>
        <h2 className="serif" style={{ fontSize: "1.5rem", marginBottom: "0.75rem" }}>
          What Four is
        </h2>
        <p style={{ lineHeight: 1.7 }}>
          Four is four small web apps: Three Dots (reply drafting for hard
          conversations), Tag In (splitting household tasks from voice memos
          and texts), Tonight (weekly meal planning from a fridge photo or
          pantry list), and Still Here (drafting personal openers to friends
          you keep meaning to text). You paste in your own text. We send it
          through an AI to get a draft. You send or use the draft, or you do
          not. We never publish anything on your behalf.
        </p>
      </section>

      <section>
        <h2 className="serif" style={{ fontSize: "1.5rem", marginBottom: "0.75rem" }}>
          Your account
        </h2>
        <ul style={{ paddingLeft: "1.2rem", lineHeight: 1.7 }}>
          <li>You need an email and a password.</li>
          <li>You are responsible for keeping your password to yourself.</li>
          <li>You can delete your account at any time by emailing us.</li>
          <li>One account per person. We do not support shared logins.</li>
        </ul>
      </section>

      <section>
        <h2 className="serif" style={{ fontSize: "1.5rem", marginBottom: "0.75rem" }}>
          Subscriptions
        </h2>
        <ul style={{ paddingLeft: "1.2rem", lineHeight: 1.7 }}>
          <li>Each app has a free tier and a paid unlimited plan.</li>
          <li>Paid plans are $5 or $9 per month, billed through Stripe.</li>
          <li>Cancel any time from the account page. Access continues until the end of the billing period.</li>
          <li>No refunds for partial months.</li>
          <li>We may change pricing with 30 days notice. Existing subscribers keep their price for 12 months from the change date.</li>
        </ul>
      </section>

      <section>
        <h2 className="serif" style={{ fontSize: "1.5rem", marginBottom: "0.75rem" }}>
          What you cannot do
        </h2>
        <ul style={{ paddingLeft: "1.2rem", lineHeight: 1.7 }}>
          <li>Use the AI drafts to harass, threaten, or impersonate anyone.</li>
          <li>Use the AI to generate spam, malware, or content that is illegal where you live.</li>
          <li>Try to break the site, scrape it, or use it to train another model.</li>
          <li>Resell the AI outputs commercially (they are for your own use).</li>
        </ul>
      </section>

      <section>
        <h2 className="serif" style={{ fontSize: "1.5rem", marginBottom: "0.75rem" }}>
          The AI is a draft, not a guarantee
        </h2>
        <p style={{ lineHeight: 1.7 }}>
          The replies, openers, and suggestions are generated by an AI. They
          may sometimes be off, rude, or just wrong. Read them. Edit them.
          Trust yourself. We are not liable for what you do with a draft, but
          we do want to hear about it if something felt off so we can fix the
          prompt.
        </p>
      </section>

      <section>
        <h2 className="serif" style={{ fontSize: "1.5rem", marginBottom: "0.75rem" }}>
          Uptime
        </h2>
        <p style={{ lineHeight: 1.7 }}>
          We try hard to keep the site up. Sometimes it will not be. We do not
          offer SLAs. If something is broken, email us and we will fix it.
        </p>
      </section>

      <section>
        <h2 className="serif" style={{ fontSize: "1.5rem", marginBottom: "0.75rem" }}>
          Changes to these terms
        </h2>
        <p style={{ lineHeight: 1.7 }}>
          We will email you at least 30 days before any material change. If you
          do not agree, you can cancel and delete your account.
        </p>
      </section>

      <section>
        <h2 className="serif" style={{ fontSize: "1.5rem", marginBottom: "0.75rem" }}>
          Contact
        </h2>
        <p style={{ lineHeight: 1.7 }}>
          Questions: <a href="mailto:hello@omicron.ink">hello@omicron.ink</a>.
        </p>
      </section>
    </div>
  );
}
